export const cards = [
  {
    id: 0,
    title: "Первый товар",
    price: "170 ₽",
    place: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    img: "/images/card.svg",
    desription: "Котик говорит мяу))",
  },
  {
    id: 1,
    title: "Второй товар",
    price: "171 ₽",
    place: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    img: "/images/card.svg",
    desription: "Котик говорит мяу))",
  },
  {
    id: 2,
    title: "Третий товар",
    price: "172 ₽",
    place: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    img: "/images/card.svg",
    desription: "Котик говорит мяу))",
  },
  {
    id: 3,
    title: "Четвертый товар",
    price: "173 ₽",
    place: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    img: "/images/card.svg",
    desription: "Котик говорит мяу))",
  },
  {
    id: 4,
    title: "Пятый товар",
    price: "174 ₽",
    place: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    img: "/images/card.svg",
    desription: "Котик говорит мяу))",
  },
  {
    id: 5,
    title: "Шестой товар",
    price: "175 ₽",
    place: "Казань, р-н Вахитовский",
    date: "10 июля 11:39",
    img: "/images/card.svg",
    desription: "Котик говорит мяу))",
  },
];
